### ISSUE TITLE
Confusion about TOTP

### ISSUE THREAD

**Issue by mehere** [itsjafer/schwab-api#5]
This project is awesome. Could you help illustrate more about TOPT in the example?

TOTP could be generated by the following and be added to the authenticator app. However where do we input the OTP generated in the authenticator app into https://github.com/itsjafer/schwab-api/blob/main/Schwab_API_Example.ipynb ?
```
from schwab_api import generate_totp

symantec_id, totp_secret = generate_totp()
```

Thanks!

**Comment by itsjafer** [comment]
Great question! Here's why we use TOTP authentication: If we use a TOTP to login, we don't need to manually take an SMS code as input everytime we login because we can programmatically generate the one-time 6-digit passcode.

There are two components to doing this:

1. the TOTP secret: this is the super long key that's generated. This is the string that you provide to the schwab API so it can automatically generate the 6 digit codes without your manual input.
2. your authenticator app: next time you want to login through the normal schwab website, it'll ask you for the one-time passcode. You'll need the authenticator app in order to generate the code when not using this API!

So in summary:

1. Generate a TOTP secret and symantec ID using the code above.
2. Enter the symantec ID on your schwab security center
3. Write down the TOTP secret somewhere in your notes as well as input it into your authenticator app
4. When using the schwab_api, provide your username, password, and TOTP secret so that the API can login (you don't need to worry about the six digit code, the API will generate that automatically)
5. When logging in normally, you'll need the authenticator app to generate the TOTP code

You asked where do we enter the TOTP secret into the codelab, we input it here:
```
# Login using playwright
print("Logging into Schwab")
logged_in = api.login(
    username=username,
    password=password,
    totp_secret=totp_secret # Get this by generating TOTP at https://itsjafer.com/#/schwab
)
```

**Comment by mehere** [comment]
Thanks a lot for the explanation - never noticed that schwab has such an option in the security center.

**Comment by davidkrum** [comment]
This project is great! Was wondering if there is any plan to add support for limit orders. Unless I am missing something, I only see the the possibility of placing market orders.
